### ISSUE TITLE
Add sendFrom method to AVAILABLE_METHODS

### ISSUE THREAD

**Issue by vizitiuRoman** [tacyarg/litecoin-core#2]
Add sendFrom method to AVAILABLE_METHODS

arguments:
    - <fromaccount> <tolitecoinaddress> <amount> [minconf=1] [comment] [comment-to]

<amount> is a real and is rounded to 8 decimal places. Will send the given amount to the given address, ensuring the account has a valid balance using [minconf] confirmations. Returns the transaction ID if successful (not in JSON object).

**Comment by tacyarg** [comment]
The method is now included.
